### ISSUE TITLE
Error When Node Lacks getAttribute Method

### ISSUE THREAD

**Issue by machineghost** [matths/knockout-experiments#1]
First off, thanks for providing this library (the Knockout people were clearly smoking something when they came up with the `params=` syntax).  You rock.

However, when I first tried to use it I got an error in the `_nodeIsCustomComponentElement` method because one of the nodes passed in (I'm guessing a comment node) did not have that method.  Of course, since a node without that method can't possibly be a custom element, I was able to fix the problem by simply adding the following check:

```
function _nodeIsCustomComponentElement (node) {
    if (!node.getAttribute) return false; // my new line
    var noParams = node.getAttribute('params') === null;
```

Just thought you might want to add it to the library proper, and since I didn't want to hassle with a pull request for just a single line ...

**Comment by matths** [comment]
@machineghost Thank you very much, I didn't expect someone to actually star this repo. Nice find! I think to add some of my other knockout findings soon, though.
I added your check (ed631695281c8de8c112448cb9d171dc5ba41b5d) in a slightly different way. It's still followed by a nodeType check, so Text nodes should return false, though.
Br,
@matths

**Comment by machineghost** [comment]
Great, thanks for implementing a fix.
